server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:./users
    username: petgo
    password: petgo

  h2:
    console:
      enabled: true
      path: /h2-console