server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  version: v1

email:
  confirmation: /registrationConfirm?token=
  expiration: 1

# Bound for generating random number for default username ending
bound: 1000

---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:./users
    username: petgo

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: petgotest@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  url: http://localhost:8081/

---
spring:
  profiles: test

app:
  url: http://localhost:8081/
