server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Bound for generating random number for default username ending
bound: 1000

---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:./users
    username: petgo
    password: petgo

  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: test
